♻️ Synced AM 📦 <-- [Sync locale files] ⌚

diff --git a/APP-MANAGER b/APP-MANAGER
--- a/APP-MANAGER
+++ b/APP-MANAGER
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 
-AMVERSION="10.1-4"
+AMVERSION="10.1.1"
 
 # Determine main repository and branch
 AMREPO="https://raw.githubusercontent.com/pkgforge-community/AM-HF-SYNC/main"
@@ -492,10 +492,165 @@ _validate_and_download_lists_of_archived_and_obsolete_apps() {
 
 # SAFETY CHECKS
 
+# Function to check online connections (uses github.com by default, as the database and CLI itself are stored/hosted there)
+_online_check_tool() {
+	if command -v wget >/dev/null 2>&1; then
+		wget -q --tries=10 --timeout=20 --spider https://github.com
+	elif command -v curl >/dev/null 2>&1; then
+		curl --output /dev/null --silent --head --fail https://github.com 1> /dev/null
+	else
+		printf $" ${RED}💀 ERROR! MISSING ESSENTIAL COMMANDS\033[0m: %s\n\n Install the above and try again! \n" "$(echo "curl, wget")"
+		exit 0
+	fi
+}
+
+_online_check() {
+	if ! _online_check_tool; then
+		printf $"\n %b is offline, please check your internet connection and try again\n\n" "$AMCLI"
+		exit 0
+	fi
+}
+
+_checksum_on_standard_dependencies() {
+	if [ -f "$CACHEDIR"/AMCACHEPATH/"$name" ]; then
+		dep_sum256_local=$(sha256sum "$CACHEDIR"/AMCACHEPATH/"$name" 2>/dev/null | awk '{print $1}')
+		dep_sum256_host=$(sort "$AMCACHEDIR/$ARCH.sha256sum.txt" | grep "$name-$ARCH-static$" 2>/dev/null | awk '{print $1}')
+		if [ "$dep_sum256_local" != "$dep_sum256_host" ]; then
+			rm -Rf "$CACHEDIR"/AMCACHEPATH/"$name"
+			_deps_dl && chmod a+x "$CACHEDIR"/AMCACHEPATH/"$name"
+		fi
+	fi
+}
+
+# Use static binaries as a fallback solution in case there are no dependencies
+AM_core_dependencies="cat chmod chown curl grep sed wget"
+AM_opt_dependencies="7z ar column du file md5sum notify-send sha1sum sha256sum sha512sum tar unxz unzip xz xzcat"
+AM_standard_dependencies="$AM_core_dependencies $AM_opt_dependencies"
+_deps_dl() {
+	if command -v curl >/dev/null 2>&1; then
+		curl -Lo "$CACHEDIR"/AMCACHEPATH/"$name" "$AM_UTILS_SOURCE/$name-$ARCH-static" 2>/dev/null
+	elif command -v wget >/dev/null 2>&1; then
+		wget -q "$AM_UTILS_SOURCE/$name-$ARCH-static" -O "$CACHEDIR"/AMCACHEPATH/"$name"
+	fi
+}
+
+if uname | grep -q BSD; then
+	missing_cmd_msg_header=$(echo $"The following commands may be missing or may not be GNU-compatible and can be temporarily downloaded from https://github.com/ivan-hc/am-utils as static binaries")
+else
+	missing_cmd_msg_header=$(echo $"The following commands are missing and can be temporarily downloaded from https://github.com/ivan-hc/am-utils as static binaries")
+fi
+missing_cmd_msg_footer=$(echo $"Press \"Y\" to store them in cache until you clear it (with \"-c\" option) or install them (ideally via your package manager). Press \"N\" to ignore this message (default).")
+
+_collect_fallback_dependencies() {
+	if [ -z "$fallback_binaries_needed" ]; then
+		fallback_binaries_needed="$name"
+	else
+		fallback_binaries_needed=$(echo "$fallback_binaries_needed $name" | tr ' ' '\n' | sort | xargs)
+	fi
+}
+
+if [ "$ARCH" = aarch64 ] || [ "$ARCH" = x86_64 ]; then
+	mkdir -p "$CACHEDIR"/AMCACHEPATH
+	# Download static binaries if commands are not available
+	amutils="$AM_standard_dependencies"
+	AM_UTILS_SOURCE="https://github.com/ivan-hc/am-utils/releases/download/continuous-$ARCH"
+	for name in $amutils; do
+		if ! command -v "$name" >/dev/null 2>&1; then
+			if [ -d "$CACHEDIR"/AMCACHEPATH/"$name" ] || [ -L "$CACHEDIR"/AMCACHEPATH/"$name" ] || [ ! -f "$CACHEDIR"/AMCACHEPATH/"$name" ]; then
+				rm -Rf "$CACHEDIR"/AMCACHEPATH/"$name"
+				_collect_fallback_dependencies
+			fi
+		fi
+		if uname | grep -q BSD; then
+			if [ -d "$CACHEDIR"/AMCACHEPATH/"$name" ] || [ -L "$CACHEDIR"/AMCACHEPATH/"$name" ] || [ ! -f "$CACHEDIR"/AMCACHEPATH/"$name" ]; then
+				case $name in
+  					'column'|'du')
+  						if ! "$name" --version 2>/dev/null; then
+  							_collect_fallback_dependencies
+  						fi
+  						;;
+  				esac
+  			fi
+		fi
+	done
+	if [ -n "$fallback_binaries_needed" ] && [ ! -f "$AMDATADIR"/disable-dependencies-prompt ]; then
+		printf "%b\n%b:\n %b\n%b\n\033[0m\n%b\n\n" "$DIVIDING_LINE" "$missing_cmd_msg_header" "${Green}" "$fallback_binaries_needed" "$missing_cmd_msg_footer" | _fit
+		read -r -p $" Do you wish to continue? (N/y): " yn
+		if echo "$yn" | grep -qi "^y"; then
+			printf "\n"
+			_online_check
+			for name in $fallback_binaries_needed; do
+				_deps_dl && chmod a+x "$CACHEDIR"/AMCACHEPATH/"$name" && printf $" - %b, downloaded from https://github.com/ivan-hc/am-utils\n" "$name" &
+			done
+			wait
+			printf "\n%b\n" "$DIVIDING_LINE"
+		else
+			[ ! -f "$AMDATADIR"/disable-dependencies-prompt ] && touch "$AMDATADIR"/disable-dependencies-prompt
+		fi
+	elif [ -z "$fallback_binaries_needed" ] && [ -f "$AMDATADIR"/disable-dependencies-prompt ]; then
+		rm -f "$AMDATADIR"/disable-dependencies-prompt
+	elif [ -f "$AMDATADIR"/disable-dependencies-prompt ]; then
+		printf "%b\n" "$DIVIDING_LINE"
+		printf $"Missing command(s): %b%b\033[0m\n" "${Green}" "$fallback_binaries_needed" | _fit
+		printf "%b\n" "$DIVIDING_LINE"
+	fi
+	# Remove static binaries and other temporary utilities if related commands are already available in PATH
+	amutils="appimagetool $amutils"
+	for name in $amutils; do
+		if command -v "$name" >/dev/null 2>&1; then
+			if uname | grep -q BSD; then
+				case $name in
+  					'column'|'du')
+  						if "$name" --version >/dev/null 2>&1; then
+  							rm -Rf "$CACHEDIR"/AMCACHEPATH/"$name"
+  						fi
+  						;;
+  					*)
+  						rm -Rf "$CACHEDIR"/AMCACHEPATH/"$name"
+  						;;
+  				esac
+			else
+				if [ -f "$CACHEDIR"/AMCACHEPATH/"$name" ]; then
+					rm -Rf "$CACHEDIR"/AMCACHEPATH/"$name"
+				fi
+			fi
+			wait
+		fi
+	done
+	# Check AMCACHEPATH integrity
+	am_bins_allowed=$(echo "$amutils" | tr ' ' '\n' | sed "s#^#$CACHEDIR/AMCACHEPATH/#g")
+	am_bins_all=$(find "$CACHEDIR"/AMCACHEPATH -mindepth 1 -maxdepth 1 \( -type d -o -type f -o -type l \))
+	if [ -n "$am_bins_all" ]; then
+		for f in "$CACHEDIR"/AMCACHEPATH/*; do
+			am_bin_item=$(echo "$f" | sed 's:.*/::')
+			if ! echo "$am_bins_allowed" | grep -q "$am_bin_item$" 2>/dev/null; then
+				rm -Rf "$f"
+			fi
+		done
+	fi
+	# Check binaries integrity
+	if [ "$(ls -A "$CACHEDIR"/AMCACHEPATH 2>/dev/null)" ]; then
+		if [ ! -f "$AMCACHEDIR"/"$ARCH".sha256sum.txt ]; then
+			if curl --output /dev/null --silent --head --fail https://github.com 1> /dev/null; then
+				deps_sum256_all=$(curl -Ls "$AM_UTILS_SOURCE/$ARCH.sha256sum.txt" 2>/dev/null)
+				if [ -n "$deps_sum256_all" ]; then
+					echo "$deps_sum256_all" > "$AMCACHEDIR"/"$ARCH".sha256sum.txt
+				fi
+			fi
+		fi
+		if [ -f "$AMCACHEDIR"/"$ARCH".sha256sum.txt ]; then
+			for name in $AM_standard_dependencies; do
+				_checksum_on_standard_dependencies &
+			done
+			wait
+			export PATH="$CACHEDIR"/AMCACHEPATH/:"${PATH}"
+		fi
+	fi
+fi
+
 # Check for essential commands required by the application
 missing_deps=""
-AMDEPENDENCES="cat chmod chown curl grep sed wget"
-for name in $AMDEPENDENCES; do
+for name in $AM_core_dependencies; do
 	if ! command -v "$name" >/dev/null 2>&1; then
 		missing_deps="$name $missing_deps"
 	fi
@@ -506,7 +661,7 @@ if [ -n "$missing_deps" ]; then
 	echo "$DIVIDING_LINE"
 	printf $" ${RED}💀 ERROR! MISSING ESSENTIAL COMMANDS\033[0m: %s\n\n Install the above and try again! \n" "${missing_deps[*]}"
 	echo "$DIVIDING_LINE"
-	printf $"%bList of the %b core dependences\033[0m:\n\n%b\n" "${Green}" "$AMCLIUPPER $AMVERSION" "$AMDEPENDENCES" | _fit
+	printf $"%bList of the %b core dependences\033[0m:\n\n%b\n" "${Green}" "$AMCLIUPPER $AMVERSION" "$AM_core_dependencies" | _fit
 	echo "$DIVIDING_LINE"
 	printf $"If this message appears it is because you are missing some dependency and if its the first time its because something new has been introduced.\n\n" | _fit
 	printf $" See %bhttps://github.com/pkgforge-community/AM-HF-SYNC#installation\033[0m for more information\n" "${LightBlue}"
@@ -533,29 +688,19 @@ _check_fedora_mess() {
 	fi
 }
 
-# Function to check online connections (uses github.com by default, as the database and CLI itself are stored/hosted there)
-_online_check() {
-	if ! wget -q --tries=10 --timeout=20 --spider https://github.com; then
-		printf $"\n %b is offline, please check your internet connection and try again\n\n" "$AMCLI"
-		exit 0
-	fi
-}
-
-# Check AMCACHEPATH integrity
-if [ -d "$CACHEDIR"/AMCACHEPATH ]; then
-	am_bins_allowed=$(echo "appimagetool" | tr ' ' '\n' | sed "s#^#$CACHEDIR/AMCACHEPATH/#g")
-	am_bins_all=$(find "$CACHEDIR"/AMCACHEPATH -mindepth 1 -maxdepth 1 \( -type d -o -type f -o -type l \))
-	for f in $am_bins_all; do if ! echo "$am_bins_allowed" | grep -q "$f$" 2>/dev/null; then rm "$f" 2>/dev/null; fi; done
-fi
-
 # Check if appimagetool is installed, and if it is not installed, download and use it where it is needed
 _download_appimagetool() {
 	_determine_args
+	if [ -f "$CACHEDIR"/AMCACHEPATH/appimagetool ]; then
+		if ! head -c10 "$CACHEDIR"/AMCACHEPATH/appimagetool 2>/dev/null | grep -qa '^.ELF....AI$'; then
+			rm -f "$CACHEDIR"/AMCACHEPATH/appimagetool
+		fi
+	fi
 	if ! command -v appimagetool >/dev/null 2>&1; then
 		mkdir -p "$CACHEDIR"/AMCACHEPATH
 		if [ ! -f "$CACHEDIR"/AMCACHEPATH/appimagetool ]; then
 			_online_check
-			wget -q https://github.com/AppImage/appimagetool/releases/download/continuous/appimagetool-"$(uname -m)".AppImage -O "$CACHEDIR"/AMCACHEPATH/appimagetool
+			wget -q https://github.com/AppImage/appimagetool/releases/download/continuous/appimagetool-"${ARCH}".AppImage -O "$CACHEDIR"/AMCACHEPATH/appimagetool
 			chmod a+x "$CACHEDIR"/AMCACHEPATH/appimagetool
 		fi
 	fi
@@ -1659,7 +1804,15 @@ _update_print_updated_apps_table() {
 	app_header=$(printf $"App")
 	old_header=$(printf $"Previous")
 	new_header=$(printf $"Current")
-	diff "$OLDVER" "$NEWVER" | grep "^>" | sed 's/^> //g' | while IFS= read -r updated_app; do
+	awk '
+	NR==FNR { a[NR]=$0; next }
+	{
+		if ($0 != a[FNR]) {
+			print "< " a[FNR]
+			print "> " $0
+		}
+	}
+	' "$OLDVER" "$NEWVER" | grep "^>" | sed 's/^> //g' | while IFS= read -r updated_app; do
 		arg=$(printf "%s\n" "$updated_app" | awk '{print $2}')
 		old_app=$(grep -F " ◆ $arg " "$OLDVER" | head -1)
 		old_version=$(printf "%s\n" "$old_app" | sed "s/^ ◆ $arg //; s/\x1b\[[0-9;]*m//g; s/[✖✓🔒]//g; s/  */ /g; s/ $//")
@@ -1697,7 +1850,7 @@ _update_determine_apps_version_changes() {
 		_update_list_updatable_apps
 		OLDVER="$AMCACHEDIR/updatable-args-list-old"
 		NEWVER="$AMCACHEDIR/updatable-args-list"
-		if cmp --silent -- "$NEWVER" "$OLDVER"; then
+		if [ "$(sort "$NEWVER")" = "$(sort "$OLDVER")" ]; then
 			printf $" Nothing to do here! \n"
 		else
 			printf $" The following apps have been updated:\n\n"
