♻️ Synced AM 📦 <-- [Sync locale files] ⌚

diff --git a/APP-MANAGER b/APP-MANAGER
--- a/APP-MANAGER
+++ b/APP-MANAGER
@@ -25,12 +25,12 @@ basename() {
 	if [ "$1" = "--" ]; then
 		dir=${2%"${2##*[!/ ]}"}
 		dir=${dir##*/}
-		dir=${dir%"${3:-}"} 
+		dir=${dir%"${3:-}"}
 		printf '%s\n' "${dir:-/}"
 	else
 		dir=${1%"${1##*[!/ ]}"}
 		dir=${dir##*/}
-		dir=${dir%"${2:-}"} 
+		dir=${dir%"${2:-}"}
 		printf '%s\n' "${dir:-/}"
 	fi
 }
@@ -219,7 +219,7 @@ fi
 _use_translate() {
 	echo "$DIVIDING_LINE"
 	if [ -z "$2" ]; then
-		printf $"Add a suitable locale code, for example \"it\" for Italian\n\n" | _fit | grep .
+		printf $"Add a suitable locale code, for example \"it\" for Italian, or use the system language - \"auto\"\n\n" | _fit | grep .
 		read -r -ep $" Leave blank to use \"$CLI\" in English: " amlocale
 		if [ -z "$amlocale" ] || [ "$amlocale" = "en" ]; then
 			iso_code="en"
@@ -348,6 +348,17 @@ _appman_check() {
 		read -r -ep $" Write the path or just press enter to use default:$(printf "\n\n ")" location
 		location="$(echo "$location" | sed 's/[ \t]/-/g; s|^\./||' 2>/dev/null)"
 		[ -z "$location" ] && location="$HOME/Applications"
+		if printf '%s' "$location" | grep -q '`\|\$(\|"\|\\'; then
+			echo "$DIVIDING_LINE"
+			echo $" 💀 ERROR: unsupported characters in path, please use a plain path"
+			echo "$DIVIDING_LINE"
+			exit 1
+		fi
+		case "$location" in
+			"~")   location="$HOME" ;;
+			"~/"*) location="$HOME/${location#\~/}" ;;
+		esac
+		location=$(eval "printf '%s' \"$location\"")
 		if ! echo "$location" | grep "^/" >/dev/null 2>&1; then
 			location="$HOME/$location"
 		fi
@@ -1116,7 +1127,7 @@ _check_version_filters() {
 				type[i] = 5
 			}
 		}
-		
+
 		# If same type, then choose the one with the longer length
 		if (type[0] == type[1]) {
 			if (length(version[0]) > length(version[1])) print version[0]
@@ -1598,7 +1609,7 @@ _use_relocate() {
 			APPMAN_APPS_NEW=$(sort -u "$SCRIPTDIR"/am-clone.source.appman | sed 's:.*/::' | xargs)
 			"$AMCLIPATH_ORIGIN" -i --user "$APPMAN_APPS_NEW"
 		fi
-		
+
 	fi
 }
 
@@ -2327,7 +2338,7 @@ case "$1" in
 			NOTE, \"--sandbox\" can be used as a flag in \"-i\" and \"-ia\" or can be replaced using the option \"-ias\" (aka Install AppImage & Sandbox).")
 		description_sync=$(echo $"Description: Updates this script to the latest version hosted.")
 		description_template=$(echo $"Description: Generate a custom installation script. To test the scripts, use the \"$AMCLI -i '/path/to/script'\" command or enter the directory of the script and run the \"$AMCLI -i ./script\" command, even using dedicated flags, if necessary (see \"-i\").")
-		description_translate=$(echo $"Description: Download and set one or more language packs (if available), set \"$AMCLI\" to English (default), your language or other languages.\n\nVisit https://github.com/pkgforge-community/AM-HF-SYNC/tree/$AMBRANCH/translations to get source files needed to submit new translations or to improve the existing ones.")
+		description_translate=$(echo $"Description: Let \"$AMCLI\" automatically use the language based on your system language; if \"$AMCLI\" does not have that system language, it fallbacks to English - auto (default), or manually set \"$AMCLI\" to use English or other languages - isocode.\n\nVisit https://github.com/pkgforge-community/AM-HF-SYNC/tree/$AMBRANCH/translations to get source files needed to submit new translations or to improve the existing ones.")
 		description_unhide=$(echo $"Description: Allow a hidden app to be shown and managed again (nulls \"hide\").")
 		description_unlock=$(echo $"Description: Unlock updates for the selected program (nulls \"lock\").")
 		description_update=$(echo $"Description: Update everything. Add \"--apps\" to update only the apps or write only the apps you want to update by adding their names. Add the \"--debug\" flag to view the output of AM-updater scripts. Add the \"--launcher\" flag to try to update only local AppImages integrated with the \"--launcher\" option (see \"--launcher\").")
@@ -2582,7 +2593,8 @@ case "$1" in
 			${Gold}translate, --translate\033[0m
 
 					${LightBlue}$AMCLI --translate\033[0m
-					${LightBlue}$AMCLI --translate {CODE}\033[0m
+					${LightBlue}$AMCLI --translate auto\033[0m
+					${LightBlue}$AMCLI --translate {ISOCODE}\033[0m
 
 			$description_translate
 
